<?php /** @var $block \Magento\Catalog\Block\Product\View */ ?>
<div class="sticker-buttons next-and-back-button-wrapper">
    <button id="sticker-back-step" class="back-button" type="button" style="display: none">
        <span>
            <?= $block->escapeHtml(__('Back')) ?>
        </span>
    </button>
    <button id="sticker-next-step" class="next-button" type="button" disabled>
        <span>
            <?= $block->escapeHtml(__('Next')) ?>
        </span>
    </button>
    <button type="submit"
            title="<?= $block->escapeHtml(__('Submit')) ?>"
            class="submit-button action tocart"
            id="product-addtocart-button"
            style="display: none"
            disabled>
        <span><?= $block->escapeHtml(__('Submit')) ?></span>
    </button>
</div>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
