<div class="chosen-values">
    <h3 class="values-header">Your Order</h3>
    <div class="values">
        <div class="value checked">
            <span class="value-text">Shape</span>
            <span class="selected-value">Circle</span>
        </div>
        <div class="value checked">
            <span class="value-text mini">Type</span>
            <span class="selected-value">Clear</span>
        </div>
        <div class="value checked">
            <span class="value-text mini">Size</span>
            <span class="selected-value size">2x2</span>
        </div>
        <div class="value checked">
            <span class="value-text quantity">Quantity</span>
            <span class="selected-value">50</span>
        </div>
        <div class="value">
            <span class="value-text">Upload</span>
        </div>
    </div>
</div>
