<?php
/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();
$product = $_item->getProduct();
/** @var $viewModel \Labelin\Sales\ViewModel\Order\Item\Renderer\DefaultRenderer */
$viewModel = $block->getViewModel();
?>
<tr id="order-item-row-<?= (int)$_item->getId() ?>">
    <td class="col name" data-th="<?= $block->escapeHtml(__('ID')) ?>">
        <strong class="product name product-item-name"><?= $block->escapeHtml($_item->getId()) ?></strong>
    </td>
    <td class="col name" data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>">
        <strong class="product name product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
        <?php if ($_options = $block->getItemOptions()): ?>
            <dl class="item-options">
                <?php foreach ($_options as $_option): ?>
                    <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                    <?php if (!$block->getPrintStatus()): ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dd<?= (isset($_formatedOptionValue['full_view']) ? ' class="tooltip wrapper"' : '') ?>>
                            <?php if (!empty($_option['option_type']) && $_option['option_type'] === 'file'): ?>
                                <?php continue;?>
                                <?= $block->getChildBlock('artwork')->setData(['item' => $_item])->toHtml(); ?>
                            <?php else : ?>
                                <?= $block->escapeHtml($_option['print_value'] ?? $_option['value']) ?>
                            <?php endif; ?>
                        </dd>
                    <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($viewModel->isPremadeProduct($_item)): ?>
                    <dd>
                        <?= $block->getChildBlock('simple_product_image_render')->setData('item', $_item)->toHtml(); ?>
                    </dd>
                <?php endif;?>
            </dl>
        <?php endif; ?>

        <br/>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock): ?>
            <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?= $block->escapeHtmlAttr(__('SKU')) ?>"><?= /* @noEscape */ $block->prepareSku($block->getSku()) ?></td>
    <td class="col price" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
        <?= $block->getItemPriceHtml() ?>
    </td>
    <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>">
        <ul class="items-qty">
            <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
                <li class="item">
                    <span class="title"><?= $block->escapeHtml(__('Ordered')) ?></span>
                    <span class="content"><?= (float)$block->getItem()->getQtyOrdered() ?></span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyShipped() > 0): ?>
                <li class="item">
                    <span class="title"><?= $block->escapeHtml(__('Shipped')) ?></span>
                    <span class="content"><?= (float)$block->getItem()->getQtyShipped() ?></span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyCanceled() > 0): ?>
                <li class="item">
                    <span class="title"><?= $block->escapeHtml(__('Canceled')) ?></span>
                    <span class="content"><?= (float)$block->getItem()->getQtyCanceled() ?></span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyRefunded() > 0): ?>
                <li class="item">
                    <span class="title"><?= $block->escapeHtml(__('Refunded')) ?></span>
                    <span class="content"><?= (float)$block->getItem()->getQtyRefunded() ?></span>
                </li>
            <?php endif; ?>
        </ul>
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>">
        <?= $block->getItemRowTotalHtml() ?>
    </td>
    <?php foreach ($_options as $_option): ?>
    <?php if (!empty($_option['option_type']) && $_option['option_type'] === 'file'): ?>
    <tr>
        <td colspan="6" align="center" valign="center" style="width:100%; background-color: #FFFFFF;">

                <?php echo $block->getChildBlock('artwork')->setData(
                    [
                        'item' => $_item,
                        'width' => $viewModel::ARTWORK_FRONT_WIDTH,
                    ]
                )->toHtml(); ?>

        </td>
    </tr>
    <tr>
        <td>
            <?php if ($artworkFormWrapperBlock = $block->getChildBlock('artwork_forms_wrapper')): ?>
                <?= $artworkFormWrapperBlock->setData('item', $_item)->toHtml(); ?>
            <?php endif; ?>
        </td>
    </tr>
<?php endif; ?>
<?php endforeach; ?>
</tr>
