<?php
/** @var $block Labelin\Sales\Block\Order\Item\Renderer\DefaultRenderer\ArtWork */
$this->parseItemOptions();
?>
<embed
    src="<?= /* @noEscape */ $block->getArtworkUrl() ?>"
    type="<?= /* @noEscape */ $block->getArtworkType() ?>"
    width="<?= /* @noEscape */ $block->getArtworkWidth() ?>"
    height="<?= /* @noEscape */ $block->getArtworkHeight() ?>"
>
<br>
<a href="<?= /* @noEscape */ $block->getArtworkUrl() ?>">
    <span>Download:</span>"<?= /* @noEscape */ $block->getArtworkLabel() ?>"
</a>
