<?php
/** @var $block Labelin\Sales\Block\Adminhtml\Order\View\Column\Items\Renderer\DefaultRenderer\ArtWork */
$artworkPreviewHelper = $block->getHelper();
$initOptions = $artworkPreviewHelper->initItemOptions($block->getData('item'));
?>
<?php if ($initOptions): ?>
    <a href="<?= /* @noEscape */ $artworkPreviewHelper->getArtworkUrl() ?>"
       title="Download: <?= /* @noEscape */ $artworkPreviewHelper->getArtworkLabel() ?>">
        <embed
            src="<?= /* @noEscape */ $artworkPreviewHelper->getArtworkUrl() ?>"
            type="<?= /* @noEscape */ $artworkPreviewHelper->getArtworkType() ?>"
            width="<?= /* @noEscape */ $artworkPreviewHelper->getArtworkWidth() ?>"
            height="<?= /* @noEscape */ $artworkPreviewHelper->getArtworkHeight() ?>"
        >
        <br>
        <?= $block->escapeHtml(__('Download file:')) ?>  <?= /* @noEscape */ $artworkPreviewHelper->getArtworkLabel() ?>
    </a>
<?php endif; ?>
