<?php
/** @var $block Labelin\Sales\Block\Adminhtml\Order\View\Column\Items\Renderer\DefaultRenderer\ArtWork */
$this->parseItemOptions();
?>
<a href="<?= /* @noEscape */ $block->getArtworkUrl() ?>"
   title="Download: <?= /* @noEscape */ $block->getArtworkLabel() ?>">
    <embed
        src="<?= /* @noEscape */ $block->getArtworkUrl() ?>"
        type="<?= /* @noEscape */ $block->getArtworkType() ?>"
        width="<?= /* @noEscape */ $block->getArtworkWidth() ?>"
        height="<?= /* @noEscape */ $block->getArtworkHeight() ?>"
    >
</a>
