<div class="tooltip-wrapper">
    <img
        class="info-icon standart"
        src="<?= $this->getViewFileUrl('Labelin_ConfigurableProduct::images/source/checkouts/pick-type/info.png') ?>"
        alt="info-icon"
    />
    <img
        class="info-icon blue"
        src="<?= $this->getViewFileUrl('Labelin_ConfigurableProduct::images/source/checkouts/pick-type/info-blue.png') ?>"
        alt="info-icon"
    />
    <div class="custom-tooltip">
        <h3 class="tooltip-header">
            <?= $this->escapeHtml(__('Clear Labels')) ?>
        </h3>
        <p class="tooltip-text">
            <?= $this->escapeHtml(__('Full color labels printed on paper with a glossy finish.')) ?>
        </p>
        <ul class="tooltip-list">
            <li><?= $this->escapeHtml(__('he label looks shiny')) ?></li>
            <li><?= $this->escapeHtml(__('displays vibrant colors')) ?></li>
            <li><?= $this->escapeHtml(__('more resistance to dirt')) ?></li>
            <li><?= $this->escapeHtml(__('difficult to write on')) ?></li>
        </ul>
        <p class="tooltip-text">
            <?= $this->escapeHtml(__('This is more popular choice. Best for product and packaging labeling.')) ?>
        </p>
    </div>
</div>
