<?php /** @var $block Magento\Framework\View\Element\Template */ ?>
<?php
$infoImg = $block->getViewFileUrl('Labelin_ConfigurableProduct::images/source/checkouts/pick-type/info.png');
$infoBlueImg = $block->getViewFileUrl('Labelin_ConfigurableProduct::images/source/checkouts/pick-type/info-blue.png');
?>
<div class="tooltip-wrapper">
    <img
        class="info-icon standart"
        src="<?= /* @noEscape */ $infoImg ?>"
        alt="info-icon"
    />
    <img
        class="info-icon blue"
        src="<?= /* @noEscape */ $infoBlueImg ?>"
        alt="info-icon"
    />
    <div class="custom-tooltip">
        <h3 class="tooltip-header">
            <?= $block->escapeHtml(__('Clear Labels')) ?>
        </h3>
        <p class="tooltip-text">
            <?= $block->escapeHtml(__('Full color labels printed on paper with a glossy finish.')) ?>
        </p>
        <ul class="tooltip-list">
            <li><?= $block->escapeHtml(__('he label looks shiny')) ?></li>
            <li><?= $block->escapeHtml(__('displays vibrant colors')) ?></li>
            <li><?= $block->escapeHtml(__('more resistance to dirt')) ?></li>
            <li><?= $block->escapeHtml(__('difficult to write on')) ?></li>
        </ul>
        <p class="tooltip-text">
            <?= $block->escapeHtml(__('This is more popular choice. Best for product and packaging labeling.')) ?>
        </p>
    </div>
</div>
