<?php /** @var $block Magento\Framework\View\Element\Template */ ?>
<?php
$infoImg = $block->getViewFileUrl('Labelin_ConfigurableProduct::images/source/checkouts/pick-type/info.png');
$infoBlueImg = $block->getViewFileUrl('Labelin_ConfigurableProduct::images/source/checkouts/pick-type/info-blue.png');
?>
<div class="tooltip-wrapper">
    <img
        class="info-icon standart"
        src="<?= /* @noEscape */ $infoImg ?>"
        alt="info-icon"
    />
    <img
        class="info-icon blue"
        src="<?= /* @noEscape */ $infoBlueImg ?>"
        alt="info-icon"
    />
    <div class="custom-tooltip">
        <h3 class="tooltip-header">
            <?= $block->escapeHtml(__('Paper Labels')) ?>
        </h3>
        <p class="tooltip-text">
            <?= $block->escapeHtml(__('Full color printed on Cast Gloss Paper. This is the most popular choice.')) ?>
        </p>
        <ul class="tooltip-list">
            <li><?= $block->escapeHtml(__('the label is flat and feels soft')) ?></li>
            <li><?= $block->escapeHtml(__('cost effective choice')) ?></li>
            <li><?= $block->escapeHtml(__('colors have a dull finish')) ?></li>
            <li><?= $block->escapeHtml(__('easy to write on')) ?></li>
        </ul>
        <p class="tooltip-text">
            <?= $block->escapeHtml(
                __('Prints may looks better, especially black and whites. Best for package decorations.')
            ) ?>
        </p>
    </div>
</div>
