<div class="tooltip-wrapper">
    <img
        class="info-icon standart"
        src="<?= $this->getViewFileUrl('Labelin_ConfigurableProduct::images/source/checkouts/pick-type/info.png') ?>"
        alt="info-icon"
    />
    <img
        class="info-icon blue"
        src="<?= $this->getViewFileUrl('Labelin_ConfigurableProduct::images/source/checkouts/pick-type/info-blue.png') ?>"
        alt="info-icon"
    />
    <div class="custom-tooltip center">
        <h3 class="tooltip-header">
            <?= $this->escapeHtml(__('Waterproof Labels')) ?>
        </h3>
        <p class="tooltip-text">
            <?= $this->escapeHtml(__('Full color labels printed on a white plastic material with a waterproof seal, giving a glossy finish.')) ?>
        </p>
        <ul class="tooltip-list">
            <li><?= $this->escapeHtml(__('the label is satiny and feels polished')) ?></li>
            <li><?= $this->escapeHtml(__('most resistant')) ?></li>
            <li><?= $this->escapeHtml(__('more expensive')) ?></li>
        </ul>
        <p class="tooltip-text">
            <?= $this->escapeHtml(__('Best for cold temperatures, humid environments and liquids.')) ?>
        </p>
    </div>
</div>
