<?php /** @var $block Magento\Framework\View\Element\Template */ ?>
<?php
$infoImg = $block->getViewFileUrl('Labelin_ConfigurableProduct::images/source/checkouts/pick-type/info.png');
$infoBlueImg = $block->getViewFileUrl('Labelin_ConfigurableProduct::images/source/checkouts/pick-type/info-blue.png');
?>
<div class="tooltip-wrapper">
    <img
        class="info-icon standart"
        src="<?= /* @noEscape */ $infoImg ?>"
        alt="info-icon"
    />
    <img
        class="info-icon blue"
        src="<?= /* @noEscape */ $infoBlueImg ?>"
        alt="info-icon"
    />
    <div class="custom-tooltip center">
        <h3 class="tooltip-header">
            <?= $block->escapeHtml(__('Waterproof Labels')) ?>
        </h3>
        <p class="tooltip-text">
            <?= $block->escapeHtml(__(
                'Full color printed on white BOPP.'
            )) ?>
        </p>
        <ul class="tooltip-list">
            <li><?= $block->escapeHtml(__('the label is satiny and feels polished')) ?></li>
            <li><?= $block->escapeHtml(__('most resistant')) ?></li>
            <li><?= $block->escapeHtml(__('more expensive')) ?></li>
        </ul>
        <p class="tooltip-text">
            <?= $block->escapeHtml(__('Best for cold temperatures, humid environments and liquids.')) ?>
        </p>
    </div>
</div>
