<?php /** @var $block Magento\Framework\View\Element\Template */ ?>
<?php $helper = $this->helper(Labelin\ConfigurableProduct\Helper\ProductType::class); ?>
<script type="text/x-magento-template" id="tier-prices-template">
    <div class="header-wrapper">
        <h2 class="checkout-page-header">
            <?= $block->escapeHtml(__('Select Quantity')) ?>

            <?php if ($helper->isProductPackagingTape($block->getPrice()->getProduct())): ?>
                <?= $block->escapeHtml(__('(300 ft/roll)')) ?>
            <?php endif; ?>
        </h2>
        <p class="checkout-page-text">
            <?= $block->escapeHtml(__('The larger quantity gives the lower cost per sticker')) ?>
        </p>
    </div>
    <div class="ac-container">
        <% _.each(tierPrices, function(item, key) { %>
        <div>
            <input id="ac-<%= (key+1) %>"
                   name="accordion-<%= (key+1) %>"
                   type="radio"
                   class="ac-input"
                   <% if (key == 0) { %>
                        checked
                   <% }; %>
            />
            <label class="ac-label" for="<%= (key+1) %>"><%= item.label %></label>
            <div class="accordion-content">
                <ul class="accordion-header">
                    <li><?= $block->escapeHtml(__('Amount')) ?></li>
                    <li><?= $block->escapeHtml(__('Price')) ?></li>
                    <li><?= $block->escapeHtml(__('Price per sticker')) ?></li>
                </ul>
                <div class="radiobuttons-wrapper">
                    <% _.each(item.groupData, function(item, key) { %>
                    <div class="radio-container">
                        <input type="radio"
                               id="radio<%= (key+1) %>"
                               name="qty"
                               value="<%= item.qty %>"
                               class="radiobutton"
                        />
                        <label for="radio<%= (key+1) %>">
                            <span class="count"><%= item.qty %></span>
                            <span class="price">$<%= item.bulkPrice %></span>
                            <span class="price">$<%= item.price %></span>
                        </label>
                    </div>
                    <% }); %>
                </div>
            </div>
        </div>
        <% }); %>
    </div>
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Labelin_ConfigurableProduct/js/step-quantity": {}
        }
    }
</script>
<div data-role="tier-price-block"></div>
