<?php /** @var $block Magento\Shipping\Block\Adminhtml\Order\Packaging */ ?>
<?php
$shippingMethod = $block->getShipment()->getOrder()->getShippingMethod();
$sizeSource = $block->getSourceSizeModel()->toOptionArray();
$girthEnabled = $block->isDisplayGirthValue() && $block->isGirthAllowed() ? 1 : 0;
?>
<?php /* @var $viewModel \Labelin\PitneyBowesShipping\ViewModel\Shipment */ ?>
<?php $viewModel = $block->getViewModel() ?>
<?php $shippingHelper = $viewModel->getShippingHelper() ?>
<script>
    require([
        "jquery",
        "prototype",
        "Magento_Shipping/order/packaging",
        "Labelin_PitneyBowesShipping/order/packaging-rates",
        "Magento_Ui/js/modal/modal"
    ], function(jQuery){
        window.packaging = new Packaging(<?= /* @noEscape */ $block->getConfigDataJson() ?>);

        window.packagingRates = new PackagingRates(<?= /* @noEscape */ $block->getConfigDataJson() ?>);

        packaging.changeContainerType($$('select[name=package_container]')[0]);
        packaging.checkSizeAndGirthParameter(
            $$('select[name=package_container]')[0],
            <?= /* @noEscape */ $girthEnabled ?>
        );
        packaging.setConfirmPackagingCallback(function(){
            packaging.setParamsCreateLabelRequest($('edit_form').serialize(true));
            packaging.sendCreateLabelRequest();
        });
        packaging.setLabelCreatedCallback(function(response){
            setLocation("<?= $block->escapeJs($block->escapeUrl($block->getUrl(
                'sales/order/view',
                ['order_id' => $block->getShipment()->getOrderId()]
            ))); ?>");
        });
        packaging.setCancelCallback(function() {
            if ($('create_shipping_label')) {
                packaging.cleanPackages();
                $('create_shipping_label').checked = false;
                toggleCreateLabelCheckbox();
            }
        });
        packaging.setItemQtyCallback(function(itemId){
            var item = $$('[name="shipment[items]['+itemId+']"]')[0];
            if (item && !isNaN(item.value)) {
                return item.value;
            }
        });
        jQuery('#packaging_window').modal({
            type: 'slide',
            title: '<?= $block->escapeJs($block->escapeHtml(__('Create Packages'))) ?>',
            buttons: [{
                text: '<?= $block->escapeJs($block->escapeHtml(__('Cancel'))) ?>',
                'class': 'action-secondary',
                click: function () {
                    packaging.cancelPackaging();
                    this.closeModal();
                    }
                }, {
                text: '<?= $block->escapeJs($block->escapeHtml(__('Save'))) ?>',
                'attr': {'disabled':'disabled', 'data-action':'save-packages'},
                'class': 'action-primary _disabled',
                click: function () {
                    packaging.confirmPackaging();
                    }
                }, {
                    text: '<?= $block->escapeJs($block->escapeHtml(__('Add Package'))) ?>',
                    'attr': {'data-action':'add-packages'},
                    'class': 'action-secondary',
                    click: function () {
                        packaging.newPackage();
                    }
            }]
        });
        jQuery(document).trigger('packaging:inited');
        jQuery(document).data('packagingInited', true);
    });
</script>
<?php if($shippingHelper->isPitneyBowesShippingByShipment($block->getShipment())): ?>
    <?php include ($block->getTemplateFile('Labelin_PitneyBowesShipping::order/packaging/popup_content.phtml')) ?>
<?php else: ?>
    <?php include ($block->getTemplateFile('Magento_Shipping::order/packaging/popup_content.phtml')) ?>
<?php endif; ?>
