<?php /** @var $block \Labelin\Checkout\Block\Success\Favourite */ ?>
<?php if ($block->isAvailable()): ?>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $block->escapeUrl($block->getFavouriteUrl()) ?>">
                <span><?= $block->escapeHtml(__('Add To Favourite List')) ?></span>
            </a>
        </div>
    </div>
    <br/>
<?php endif; ?>
