<?php /** @var \Magento\Contact\Block\ContactForm $block */ ?>
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <div class="questions-form">
        <div class="container">
            <h2 class="label-section-header"><?= $block->escapeHtml(__('Have Questions?')) ?></h2>
            <p class="form-text">
                <?= $block->escapeHtml(
                    __('Please feel free to contact us. Our label experts will be happy to assist you')
                ) ?>
            </p>
            <div class="inputs-group">
                <div class="inputs-wrapper">
                    <input name="name[firstname]"
                           id="firstname"
                           title="<?= $block->escapeHtmlAttr(__('First Name')) ?>"
                           placeholder="<?= $block->escapeHtmlAttr(__('First Name *')) ?>"
                           class="input-text form-input"
                           type="text"
                           data-validate="{required:true}"/>
                    <input name="telephone" id="telephone" class="input-text form-input" type="text"
                           placeholder="<?= $block->escapeHtmlAttr(__('Phone')) ?>"/>
                </div>
                <div class="inputs-wrapper">
                    <input name="name[lastname]"
                           id="lastname"
                           title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>"
                           placeholder="<?= $block->escapeHtmlAttr(__('Last Name *')) ?>"
                           class="input-text form-input"
                           type="text"
                           data-validate="{required:true}"/>
                    <input name="email"
                           id="email"
                           title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                           placeholder="<?= $block->escapeHtmlAttr(__('Email *')) ?>"
                           class="input-text form-input"
                           type="email"
                           data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="textarea-wrapper">
                <textarea name="comment"
                          id="comment"
                          class="form-textarea"
                          placeholder="<?= $block->escapeHtmlAttr(__('Message *')) ?>"
                          data-validate="{required:true}"></textarea>
            </div>
            <div class="labels-button-wrapper">
                <input type="hidden" name="hideit" id="hideit" value=""/>
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr(__('Send Your Message')) ?>"
                        class="labels-button">
                    <span><?= $block->escapeHtml(__('Send Your Message')) ?></span>
                </button>
            </div>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "*": {
            "Labelin_ContactUs/js/contactUs": {}
        }
    }
</script>
