<script type="text/javascript" xml="space">
    require([
        'jquery',
        'owlcarousel'
    ], function ($) {
        $(document).ready(function () {
            $('.owl-carousel').owlCarousel({
                loop: true,
                items: 3,
                dots: false,
                autoplay: true,
                autoplayTimeout: 3000,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:1,
                        nav:false
                    },
                    768:{
                        items:2,
                        nav:false
                    },
                    1000:{
                        items:3,
                        nav: false,
                    }
                }
            })
        });
    });
</script>
