<script type="text/javascript" xml="space">
    require([
        'jquery',
        'owlcarousel'
    ], function($){
        $(document).ready(function() {
            $('.owl-carousel ').owlCarousel({
                loop:true,
                nav:false,
                items:3,
                dots:false,
                autoplay:true,
                autoplayTimeout:3000
            })
        });
    });
</script>
