<?php /** @var $block Magento\Checkout\Block\Cart\Item\Renderer\Actions\Generic */ ?>
<?php use Magento\ConfigurableProduct\Model\Product\Type\Configurable; ?>

<?php if (!$block->getItem()->getData('is_reordered') &&
    $block->getItem()->getProduct()->getTypeId() === Configurable::TYPE_CODE): ?>
    <span>
        <b><?= $block->escapeHtml(__('You will get a digital proof after your order is placed. It may take 24 -48 business hours.')) ?></b>
    </span>
<?php endif; ?>
