<?php /** @var $block Magento\Catalog\Block\Product\View */ ?>
<?php
$required = '';
if ($block->hasRequiredOptions()) {
    $required = ' data-hasrequired="' . $block->escapeHtmlAttr(__('* Required Fields')) . '"';
}
?>
<div class="product-options-wrapper" id="product-options-wrapper"<?= /* @noEscape */ $required ?>>
    <div class="fieldset" tabindex="0">
        <div id="product_options">
            <?= $block->getChildHtml('swatch_options', true) ?>
        </div>
        <div id="sticker_price" style="display: none">
            <?= $block->getChildHtml('product.price.tier', true) ?>
        </div>
        <div id="sticker_artwork" style="display: none">
            <?= $block->getChildHtml('product_options', true) ?>
        </div>
    </div>
</div>
